version: '3.8'

services:
  local_postgres:
    image: postgres:17.2
    restart: always
    container_name: ${SERVER_NAME}
    hostname: docker_${SERVER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      TZ: ${TZ}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - data_psql17:/var/lib/postgresql/data

  local_postgres_admin:
    image: dpage/pgadmin4:8.14.0
    restart: always
    container_name:  ${SERVER_NAME}_admin
    hostname: docker_${SERVER_NAME}_admin
    ports:
      - ${PGADMIN_DEFAULT_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - data_admin17:/var/lib/pgadmin
    depends_on:
      - local_postgres

volumes:
  data_psql17:
  data_admin17:

